[package]
name = "rusty_ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "play_once"
crate-type = ["cdylib"] #dynamic library

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
radio = "0.11.0" 